// Background job state for the Antigravity companion.
// One directory per job under jobsRoot(): meta.json + output.txt + err.txt + agy.log

import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
  readdirSync,
  statSync,
  rmSync,
} from "node:fs";
import { join } from "node:path";
import { jobsRoot, jobDir } from "./paths.mjs";
import { readLogSafe } from "./agy.mjs";
import { classifyRun } from "./result.mjs";

function nowIso() {
  return new Date().toISOString();
}

export function newJobId() {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return `agy-${ts}-${rand}`;
}

export function jobPaths(id, env = process.env) {
  const dir = jobDir(id, env);
  return {
    dir,
    meta: join(dir, "meta.json"),
    output: join(dir, "output.txt"),
    err: join(dir, "err.txt"),
    log: join(dir, "agy.log"),
  };
}

export function createJob(meta, env = process.env) {
  const id = meta.id || newJobId();
  const paths = jobPaths(id, env);
  mkdirSync(paths.dir, { recursive: true });
  const record = {
    id,
    kind: meta.kind || "delegate",
    title: meta.title || "",
    prompt: meta.prompt || "",
    cwd: meta.cwd || process.cwd(),
    status: meta.status || "running",
    pid: meta.pid ?? null,
    conversationId: meta.conversationId ?? null,
    startedAt: meta.startedAt || nowIso(),
    finishedAt: meta.finishedAt ?? null,
    error: meta.error ?? null,
    paths,
  };
  writeFileSync(paths.meta, JSON.stringify(record, null, 2));
  // Housekeeping, never load-bearing: a pruning failure must not fail a run.
  try {
    pruneJobs(env);
  } catch {
    /* ignore */
  }
  return record;
}

export function writeJob(job) {
  writeFileSync(job.paths.meta, JSON.stringify(job, null, 2));
  return job;
}

export function readJob(id, env = process.env) {
  const paths = jobPaths(id, env);
  if (!existsSync(paths.meta)) return null;
  try {
    const job = JSON.parse(readFileSync(paths.meta, "utf8"));
    job.paths = paths; // always recompute absolute paths
    return job;
  } catch {
    return null;
  }
}

export function isAlive(pid) {
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (e) {
    return e.code === "EPERM"; // exists but not ours
  }
}

/**
 * Terminal job status for a RunResult outcome. The single mapping — the
 * foreground path and reconcile() must never disagree about what happened.
 */
export function statusForOutcome(outcome) {
  if (outcome === "success") return "done";
  if (outcome === "empty") return "empty";
  return "failed";
}

/**
 * Reconcile a job's recorded status with reality: if it was "running" but the
 * pid is gone, classify what the run actually produced and persist a terminal
 * status.
 *
 * Note what this does NOT do: test output.txt for emptiness. Under
 * `--output-format json` a FAILED run writes a perfectly non-empty JSON blob,
 * so emptiness says nothing about success. Only classifyRun decides.
 */
export function reconcile(job) {
  if (!job) return job;
  if (job.status !== "running") return job;
  if (isAlive(job.pid)) return job;

  const run = classifyRun({
    stdout: readLogSafe(job.paths.output),
    logText: readLogSafe(job.paths.log),
    timedOut: false,
  });

  job.finishedAt = nowIso();
  job.conversationId = job.conversationId || run.conversationId;
  job.status = statusForOutcome(run.outcome);
  job.error = run.error
    ? run.error.message + (run.error.resetsIn ? ` (resets in ${run.error.resetsIn})` : "")
    : null;
  return writeJob(job);
}

// A job id is generated by newJobId(); anything else in the store was not put
// there by us. The id reaches this path from user input via readJob(id), so the
// pattern is a guard, not a formality.
const JOB_ID_RE = /^agy-[a-z0-9]+-[a-z0-9]+$/;

const DEFAULT_TTL_DAYS = 14;
const DEFAULT_MAX_JOBS = 50;

function intFromEnv(env, name, fallback) {
  const raw = env[name];
  if (raw === undefined || raw === "") return fallback;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}

/**
 * Trim the job store: drop anything older than the TTL, and anything outside
 * the newest MAX_JOBS by startedAt. Applies across every repository — the cap
 * is on the store, not per-repo.
 *
 * A running job, or one whose pid is still alive, is never deleted regardless
 * of age: a long background run must survive its own TTL.
 *
 * @param {NodeJS.ProcessEnv} [env]
 * @returns {{deleted: string[]}}
 */
export function pruneJobs(env = process.env) {
  const root = jobsRoot(env);
  const deleted = [];
  if (!existsSync(root)) return { deleted };

  const ttlDays = intFromEnv(env, "ANTIGRAVITY_CC_JOB_TTL_DAYS", DEFAULT_TTL_DAYS);
  const maxJobs = intFromEnv(env, "ANTIGRAVITY_CC_MAX_JOBS", DEFAULT_MAX_JOBS);
  const cutoff = Date.now() - ttlDays * 86_400_000;

  const candidates = [];
  for (const name of readdirSync(root)) {
    if (!JOB_ID_RE.test(name)) continue; // never touch what we did not create
    const job = readJob(name, env);
    if (!job) continue;
    const protectedJob = job.status === "running" || isAlive(job.pid);
    candidates.push({ id: name, startedAt: job.startedAt || "", protectedJob });
  }

  candidates.sort((a, b) => (a.startedAt < b.startedAt ? 1 : -1)); // newest first

  for (let i = 0; i < candidates.length; i += 1) {
    const { id, startedAt, protectedJob } = candidates[i];
    if (protectedJob) continue;
    const ts = Date.parse(startedAt);
    const tooOld = Number.isFinite(ts) && ts < cutoff;
    const beyondCap = i >= maxJobs;
    if (!tooOld && !beyondCap) continue;
    try {
      rmSync(jobDir(id, env), { recursive: true, force: true });
      deleted.push(id);
    } catch {
      /* a job we cannot delete is not a reason to fail a run */
    }
  }

  return { deleted };
}

export function listJobs(cwd, env = process.env) {
  const root = jobsRoot(env);
  if (!existsSync(root)) return [];
  const jobs = [];
  for (const name of readdirSync(root)) {
    const job = readJob(name, env);
    if (!job) continue;
    reconcile(job);
    if (cwd && job.cwd !== cwd) continue;
    jobs.push(job);
  }
  jobs.sort((a, b) => (a.startedAt < b.startedAt ? 1 : -1));
  return jobs;
}

export function latestJob(cwd, env = process.env) {
  return listJobs(cwd, env)[0] || null;
}

export function cancelJob(job) {
  if (!job) return { cancelled: false, reason: "not found" };
  if (job.status !== "running") return { cancelled: false, reason: `job is ${job.status}` };
  if (!isAlive(job.pid)) {
    job.status = "failed";
    job.finishedAt = nowIso();
    job.error = "process exited before cancel";
    writeJob(job);
    return { cancelled: false, reason: "process already exited" };
  }
  try {
    process.kill(job.pid, "SIGTERM");
  } catch {
    /* ignore */
  }
  job.status = "cancelled";
  job.finishedAt = nowIso();
  writeJob(job);
  return { cancelled: true };
}

export { nowIso };
